- name: Check to see if degrib is already installed
  stat: path=/usr/local/bin/degrib
  register: degrib_installed

- name: Download degrib
  get_url: dest=/home/cw url=http://www.nws.noaa.gov/mdl/degrib/download/degrib-src.tar.gz
  when: degrib_installed.stat.exists == false

- name: Unarchive degrib
  unarchive: src=/home/cw/degrib-src.tar.gz dest=/home/cw
  when: degrib_installed.stat.exists == false

- name: Install tcl
  apt: pkg=tcl-dev
  when: degrib_installed.stat.exists == false

- name: Copy existing compression library to src
  copy: src=/usr/lib/x86_64-linux-gnu/libz.a dest=/home/cw/degrib/src/zlib
  when: degrib_installed.stat.exists == false

- name: Make degrib
  shell: ./config-linux.sh && make || echo 0 chdir=/home/cw/degrib/src creates=/usr/local/bin/degrib 
  when: degrib_installed.stat.exists == false

- name: Copy degrib to /usr/local/bin
  shell: cp /home/cw/degrib/src/degrib/degrib /usr/local/bin
  when: degrib_installed.stat.exists == false

- name: Make sure geodata directory exists
  file: path=/home/cw/noaa/degrib/geodata state=directory owner={{ username }} group={{ username }}

- name: Copy geodata contents to geodata directory
  shell: cp /home/cw/degrib/geodata/* /home/cw/noaa/degrib/geodata
  when: degrib_installed.stat.exists == false

- name: Make sure xml directory exists
  file: path=/home/cw/noaa/xml state=directory owner={{ username }} group={{ username }}
