## file: roles/webtier/tasks/main.yml

- apt: pkg={{ item }}
  with_items:
    - python-pip
    - python-dev
    - python-virtualenv
    - build-essential
    - git
    - sphinxsearch
    - redis-server

- pip: name=pip extra_args='--upgrade'
- pip: name=virtualenvwrapper

- name: create www user user
  user: name={{ username }} generate_ssh_key=yes createhome=yes password={{ webuser_password }} shell=/bin/bash groups=www-data

- name: copy ssh private key to .ssh directory
  shell: echo "{{ ssh_private_key }}" > /home/cw/.ssh/id_rsa

- name: ensure correct permissions on private key file
  file: path=/home/cw/.ssh/id_rsa owner=cw group=cw mode=0600

- name: copy ssh public key to .ssh directory
  shell: echo "{{ ssh_public_key }}" > /home/cw/.ssh/id_rsa.pub

- name: ensure correct permissions on public key file
  file: path=/home/cw/.ssh/id_rsa.pub owner=cw group=cw mode=0644

- name: Git checkout
  sudo: yes
  sudo_user: "{{ username }}"
  git: repo=git@github.com:jonstjohn/climbingweather-web.git dest=/home/cw/climbingweather-web accept_hostkey=True version={{ git_branch }}

- name: Upgrade the virtualenv
  sudo: yes
  sudo_user: "{{ username }}"
  pip: requirements=/home/cw/climbingweather-web/requirements.txt virtualenv=/home/cw/Envs/climbingweather-web

- name: Copy additional .profile config
  template: src=".profile.j2" dest="/home/cw/.profile_additions" owner={{ username }} group={{ username }}

- name: add virtualenvwrapper to path
  lineinfile: line=". /usr/local/bin/virtualenvwrapper.sh" dest="/home/cw/.profile"

- name: add .profile_additions to .profile
  lineinfile: line=". ~/.profile_additions" dest="/home/cw/.profile"

- include: apache.yml

- include: degrib.yml
